backend:
  name: git-gateway
  branch: master
media_folder: '/public/uploads'
public_folder: '/uploads'
collections:
  - label: 'Products'
    name: 'products'
    create: true
    folder: 'content/products'
    extension: 'json'
    fields:
      - { label: ID, name: id, widget: number }
      - { label: Name, name: name, widget: string }
      - { label: Price, name: price, widget: number }
